"""Pydantic v2 models for the Daily System.

The Daily System is a gamified energy management layer over the existing
task/habit/project pipeline. Stamina is measured in real minutes — the
user's daily pool is computed once per day from sleep + energy scores
(`((sleep + energy) / 2) * 6`, capped at [0, 600]) and then drained by
completed task durations and regenerated by quick boosts (coffee, naps,
walks, etc.).

Per ADR-003 the system is single-user, so these models do not carry a
`user_id` — the service layer resolves that from the canonical row in
`users`. Per ADR-010 the underlying task table is `daily_tasks`; the
boost log lives in the new `stamina_boosts` table from migration 009.
"""

from datetime import date as DateType
from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field

__all__ = [
    "BoostType",
    "BOOST_LABELS",
    "DailyLog",
    "DailyLogCreate",
    "TaskAPItem",
    "StaminaStatus",
    "BoostAvailability",
    "BoostResult",
]


class BoostType(StrEnum):
    """The six quick-boost actions surfaced in the StaminaDetailsPanel.

    String values match the `stamina_boosts.boost_type` CHECK constraint
    introduced in migration 009.
    """

    COFFEE = "coffee"
    POWER_NAP = "power_nap"
    NAP = "nap"
    WALK = "walk"
    WATER = "water"
    MEDITATION = "meditation"


# Polish UI labels with emoji — kept next to the enum so the FE client
# and the FastAPI response can share a single source of truth.
BOOST_LABELS: dict[BoostType, str] = {
    BoostType.COFFEE: "☕ Kawa",
    BoostType.POWER_NAP: "💤 Power Nap",
    BoostType.NAP: "😴 Drzemka",
    BoostType.WALK: "🚶 Spacer",
    BoostType.WATER: "💧 Nawodnienie",
    BoostType.MEDITATION: "🧘 Medytacja",
}


# ─── Daily log ────────────────────────────────────────────────────────────────


class DailyLogCreate(BaseModel):
    """Payload for `POST /api/v1/daily/log`.

    Both scores are 0..100 sliders. The service layer computes
    `stamina_pool` deterministically — the client never sets it.
    """

    sleep_score: int = Field(ge=0, le=100)
    energy_score: int = Field(ge=0, le=100)
    notes: str | None = Field(default=None, max_length=500)


class DailyLog(BaseModel):
    """Persisted daily log row (one per user, per day)."""

    id: str
    date: DateType
    sleep_score: int = Field(ge=0, le=100)
    energy_score: int = Field(ge=0, le=100)
    stamina_pool: int = Field(ge=0, le=600)
    notes: str | None = None
    created_at: datetime


# ─── Stamina status ───────────────────────────────────────────────────────────


class TaskAPItem(BaseModel):
    """One row inside `StaminaStatus.tasks_breakdown`.

    `ap_cost` is signed — positive for draining tasks, negative for
    regenerative ones (so the FE can show the same number with a
    leading sign without recomputing).
    """

    task_id: str
    title: str
    ap_cost: int
    is_completed: bool
    is_regenerative: bool


class StaminaStatus(BaseModel):
    """Snapshot of today's stamina ledger."""

    date: DateType
    base_pool: int = Field(ge=0)
    boosts_total: int = Field(ge=0)
    ap_used: int = Field(ge=0)
    ap_restored: int = Field(ge=0)
    ap_available: int = Field(ge=0)
    percentage: float = Field(ge=0.0)
    tasks_breakdown: list[TaskAPItem] = Field(default_factory=list)
    is_initialized: bool


# ─── Boost availability & results ────────────────────────────────────────────


class BoostAvailability(BaseModel):
    """One boost button's state for the StaminaDetailsPanel."""

    boost_type: BoostType
    label: str
    ap_restored: int
    is_available: bool
    cooldown_remaining_min: int | None = None
    uses_today: int = Field(ge=0)
    max_per_day: int | None = None


class BoostResult(BaseModel):
    """Response for `POST /api/v1/daily/boosts/{type}`."""

    boost_type: BoostType
    ap_restored: int
    new_ap_available: int
    cooldown_until: datetime
